Presto connect plugin uri
fredrikhgrelland/terraform-nomad-presto pull request #31
Opened 2020-09-29 15:01 UTC by oschistad

Fixes #30

2020-10-02 05:52 UTC, oschistad commented
The test is failing because the presto service never goes online. In the coordinator logs I can see the following:
```
2020-10-02T05:44:06.940Z	ERROR	main	io.prestosql.server.Server	No service providers of type io.prestosql.spi.Plugin
java.lang.IllegalStateException: No service providers of type io.prestosql.spi.Plugin
	at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:166)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:157)
	at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:138)
	at io.prestosql.server.Server.doStart(Server.java:117)
	at io.prestosql.server.Server.lambda$start$0(Server.java:73)
	at io.prestosql.$gen.Presto_341____20201002_054313_1.run(Unknown Source)
	at io.prestosql.server.Server.start(Server.java:73)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:38)
```

This does not appear related to the changes I have made - could this be a new issue from upstream?

2020-10-07 10:21 UTC, zhenik requested changes

2020-10-07 10:21 UTC, zhenik commented on variables.tf
> +  default = "https://oss.sonatype.org/service/local/repositories/releases/content/io/github/gugalnikov/presto-consul-connect/"
host address is not correct
```suggestion
  default = "https://oss.sonatype.org/service/local/repositories/releases/content/io/github/gugalnikov/presto-consul-connect"
```

2020-10-07 11:32 UTC, zhenik requested changes

2020-10-07 11:32 UTC, zhenik commented on variables.tf
> +  default = "https://oss.sonatype.org/service/local/repositories/releases/content/io/github/gugalnikov/presto-consul-connect"
```suggestion
  description = "Artifact URI source"
  default = "https://oss.sonatype.org/service/local/repositories/releases/content/io/github/gugalnikov/presto-consul-connect"
```

2020-10-08 09:53 UTC, zhenik commented
blocker #35 

vagrant-hashistack 0.4.3 require intentions creation once consul_acl=enabled and default_policy=deny. It iwll be fix in #35 .

2020-10-08 12:12 UTC, zhenik approved these changes

2020-10-08 13:26 UTC, merged